#include<iostream>
using namespace std;
int main(){
    // char a = 'v';
    // cout<<a<<endl;
    // bool bl =true;
    // cout<<bl<<endl;
    // int size =sizeof(a);
    // cout<<"Size of A is " <<size<<endl;
    // int a = 'a';
    // cout<<a<<endl;

    // char ch=98;
    // cout<<ch<<endl;

    int n;
    cin>>n;
    // cout<<"value of n is : "<<n <<endl;
    if(n>0){
        cout<<"A is positive"<<endl;

    }




    }